### PR TITLE
Fix GetBlockVerbose API.

### LINKED ISSUE #90: `GetBlockVerbose` is broken for bitcoin core
GetBlockVerbose takes an argument `verboseTx bool`, and make the rpc call

```
{"jsonrpc":"1.0","method":"getblock","params":["0000000000000000023ce2ceba757ccca3d3ee4938608f37f1e73cd4ec3d6d59",true,verboseTx],"id":1}
```

However bitcoin core's `getblock` only takes one argument, so this gives an error

### PR DESCRIPTION
**Pull request by dajohi**
This changes the GetBlockVersion API to not send a third parameter.
The third parameter is a boolean that expands the transaction data
structures as well.  However, Bitcore Core does not recognize this
feature.

GetBlockVerbose now only takes a hash value.

Users of the GetBlockVerbose(hash, true) must now use
GetBlockVerboseTx(hash).

Fixes #90

### CODE REVIEW

**Comment by dajohi** [comment]
@frozenprincess does this work for you?  Just GetBlockVerbose(hash) now.

File: chain.go [hunk 1]
```diff
@@ -134,22 +134,66 @@ func (r FutureGetBlockVerboseResult) Receive() (*btcjson.GetBlockVerboseResult,
...
 // See GetBlock to retrieve a raw block instead.
-func (c *Client) GetBlockVerbose(blockHash *chainhash.Hash, verboseTx bool) (*btcjson.GetBlockVerboseResult, error) {
-	return c.GetBlockVerboseAsync(blockHash, verboseTx).Receive()
+func (c *Client) GetBlockVerbose(blockHash *chainhash.Hash) (*btcjson.GetBlockVerboseResult, error) {
+	return c.GetBlockVerboseAsync(blockHash).Receive()
+}
+
+// FutureGetBlockVerboseTxResult is a future promise to deliver the result of a
+// GetBlockVerboseAsync RPC invocation (or an applicable error).
+type FutureGetBlockVerboseTxResult chan *response
```
Comment (davecgh) [inline chain.go]: There is no need for a new type for this since the result is still a `*btcjson.GetBlockVerboseResult`.  In fact, you can see that it's not even used in the new functions.

File: chain.go [hunk 2]
```diff
@@ -134,22 +134,66 @@ func (r FutureGetBlockVerboseResult) Receive() (*btcjson.GetBlockVerboseResult,
...
+
+	cmd := btcjson.NewGetBlockCmd(hash, btcjson.Bool(true), btcjson.Bool(true))
+	return c.sendCmd(cmd)
+}
+
+// GetBlockVerboseTx returns a data structure from the server with information
+// about a block and its transactions given its hash.
+//
+// See GetBlock to retrieve a raw block instead.
+func (c *Client) GetBlockVerboseTx(blockHash *chainhash.Hash) (*btcjson.GetBlockVerboseResult, error) {
```
Comment (davecgh) [inline chain.go]: The comment should also call out how this is different than `GetBlockVerbose`.

File: chain.go [hunk 3]
```diff
@@ -134,22 +134,66 @@ func (r FutureGetBlockVerboseResult) Receive() (*btcjson.GetBlockVerboseResult,
...
 	return c.sendCmd(cmd)
 }
 
 // GetBlockVerbose returns a data structure from the server with information
 // about a block given its hash.
 //
 // See GetBlock to retrieve a raw block instead.
-func (c *Client) GetBlockVerbose(blockHash *chainhash.Hash, verboseTx bool) (*btcjson.GetBlockVerboseResult, error) {
-	return c.GetBlockVerboseAsync(blockHash, verboseTx).Receive()
+func (c *Client) GetBlockVerbose(blockHash *chainhash.Hash) (*btcjson.GetBlockVerboseResult, error) {
```
Comment (davecgh) [inline chain.go]: The comment should also call out how this is different than `GetBlockVerboseTx`.

Comment (dajohi) [inline chain.go]: Added

File: chain.go (hunk 1 above)
Comment (dajohi) [inline chain.go]: I kept the type and changed the function call to return FutureGetBlockVerboseTxResult instead.  It may help in debugging.

File: chain.go (hunk 2 above)
Comment (dajohi) [inline chain.go]: Added

File: chain.go (hunk 1 above)
Comment (davecgh) [inline chain.go]: I think having a separate type is simply incorrect.  The point of having different types here is to allow a specific type of return value and/or deserialization logic.   Both of those conditions are exactly the same here, so I'm not sure how it's at all beneficial to have a separate type that is identical.

Comment (dajohi) [inline chain.go]: OK.  Updated.
